version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cafecerca-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cafecercadb
      MYSQL_USER: cafecercauser
      MYSQL_PASSWORD: cafepass
    ports:
      - "3307:3306"
    volumes:
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
