CREATE DATABASE IF NOT EXISTS cafecercadb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cafecercadb;

-- Tabla de Cafeterías
CREATE TABLE IF NOT EXISTS Cafes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    horario VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de Visitas
CREATE TABLE IF NOT EXISTS Visitas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cafeteriaId INT NOT NULL,
    fecha DATETIME NOT NULL,
    calificacion INT NOT NULL,
    comentario TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cafeteriaId) REFERENCES Cafes(id)
);

-- Tabla de Imágenes de Visitas
CREATE TABLE IF NOT EXISTS VisitaImagenes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    visitaId INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (visitaId) REFERENCES Visitas(id) ON DELETE CASCADE
);

-- Tabla de Comentarios
CREATE TABLE IF NOT EXISTS Comentarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    visitaId INT NOT NULL,
    userId INT NOT NULL,
    nombreUsuario VARCHAR(255) NOT NULL,
    texto TEXT NOT NULL,
    fechaHora DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (visitaId) REFERENCES Visitas(id) ON DELETE CASCADE
);
