CREATE DATABASE IF NOT EXISTS cafecercadb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cafecercadb;

CREATE TABLE IF NOT EXISTS example_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
